language: go

install: go get -t ./...

script: make test testrace db integration

sudo: false

go:
  - 1.9

services:
  - postgresql

before_script:
  - psql -c 'create database verssion;' -U postgres
